config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  get '/signup' => 'accounts#new'
  post '/signup' => 'accounts#create'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  delete '/signout' => 'sessions#destroy'

  namespace :accounts, as: 'accounts', constraints: { id: User::USERNAME_FORMAT } do
    get '/passwords/forgot' => 'passwords#new'
    post '/passwords/forgot' => 'passwords#create'

    resources :passwords, only: [:edit, :update]
    resources :activations, only: [:new, :edit] 
  end
  
  resource :account, only: [:edit] do 
    patch '/edit', action: :update
    put '/edit', action: :update
  end

  constraints( id: /\d+/ ) do
    resources :articles
    resources :categories, only: [:create, :update, :destroy]
    resources :comments, only: [:create, :edit, :update, :destroy] do
      member do
        get :reply
      end
    end
  end

  # 上传图片
  match '/pictures' => 'pictures#create', via: [:post, :patch, :put]
  # 暂存文章/简历
  match '/holds' => 'holds#update', via: [:post, :patch, :put]

  namespace :admin, as: 'admin' do
    root 'home#index', as: 'index'
    resources :users, except: :show
    resources :articles, except: :show
    resources :categories, except: :show
    resources :tags, except: :show
    resources :comments, except: :show
    resources :pictures, only: [:index, :destroy, :create]
  end

  # users相关路由最后
  resources :users, only: [:show] , path: '' , constraints: { id: User::USERNAME_FORMAT } do
    member do
      get :categories
      get :aboutme
      get :drafts
      get :archive
      get '/categories/:category_id', as: 'category', to: 'users#category'
      get '/tags/:tag_id', as: 'tag', to: 'users#tag'
      get '/search', to: 'search#index'
      get '/resume', to: 'resumes#show'
      match '/resume', to: 'resumes#update', via: [:patch, :put]
      get '/resume/edit', to: 'resumes#edit'
    end
  end

end

app/models/article.rb
class Article < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  
  validates :title, :user_id, :category_id, presence: true
  validate :tags_number

  default_scope ->{ order created_at: :desc }
  scope :posted, -> { where posted: true }
  scope :unposted, ->{ where posted: false }

  belongs_to :user
  belongs_to :category
  has_many :article_tagships,      dependent: :destroy
  has_many :tags,                  through: :article_tagships
  has_many :article_pictureships,  dependent: :destroy
  has_many :pictures,              through: :article_pictureships
  has_many :comments,              dependent: :destroy

  attr_accessor :tagstr

  after_save :build_user_and_category_ships

  # 以字符串形式取出文章标签
  def tags2str
    self.tags.map { |tag| tag.name }.join ","
  end

  # 存储字符串形式的标签
  def str2tags(str)
    return if str.blank?
    str.split(/[,，]/).each do |tagname|
      tagname.strip!
      tag = Tag.find_or_create_by name: tagname.html_safe
      self.article_tagships.find_or_create_by tag: tag
    end
  end

  def update_tags(str)
    return if str.blank?
    return if str.strip == tags2str
    self.article_tagships.destroy_all
    str2tags str
  end

  def posted_year
    created_at.year
  end

  def comment_count
    comments.where(deleted_at: nil).size
  end

  class << self
    # 根据关键字搜索某用户已发布的文章
    # 最多返回100条记录
    def search_by_token_in_user(token, user)
      return nil if token.blank? || user.blank?
      search(
        size: 100,
        query: {
          bool: {
            must: [
              { match: { user_id: user.id } },
              { match: { posted: true } },
              { multi_match: 
                {
                  query: token.to_s,
                  fields: ['title', 'content']
                } 
              }
            ]
          }
        },
        highlight: {
          pre_tags: ["<strong>"],
          post_tags: ["</strong>"],
          number_of_fragments: 1,
          fragment_size: 100,
          fields: {
              title: { number_of_fragments: 0 },
              content: {}
          }
        }
      ).records
    end
  end

  private
    # 标签最多为5个
    def tags_number
      return if tagstr.blank?
      maximum = 5
      if tagstr.split(/[,，]/).size > maximum
        errors.add :tag, I18n.t("errors.tags_too_much", size: maximum)
      end
    end

    def build_user_and_category_ships
      unless user.categories.include? category
        user.user_categoryships.create category: category
      end
    end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::ApplicationController
  before_action :delete_cache_pictures, only: [:new, :edit, :index]

  def index
    case params[:by]
    when 'posted'
      @value = 2
      @articles = Article.posted.reorder(nil).paginate page: params[:page], per_page: MAX_IN_PAGE
    when 'unposted'
      @value = 3
      @articles = Article.unposted.reorder(nil).paginate page: params[:page], per_page: MAX_IN_PAGE
    else 
      @value = 1
      @articles = Article.all.reorder(nil).paginate page: params[:page], per_page: MAX_IN_PAGE
    end
  end

  def destroy
    @article = Article.find_by_id params[:id]
    if @article
      @article.destroy
      flash[:success] = I18n.t "flash.success.delete_article", value: @article.id
    else
      flash[:warning] = I18n.t "flash.warning.article_not_fount", value: params[:id]
    end
    redirect_to admin_articles_path
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new article_params
    if @article.save
      @article.str2tags @article.tagstr
      flash[:success] = I18n.t "flash.success.create_article"
      # 保存图片
      current_user.post_cache_pictures_in_article @article
      redirect_to admin_articles_path
    else
      flash.now[:warning] = @article.errors.full_messages[0]
      render 'new'
    end
  end

  def edit
    @article = Article.find_by_id params[:id]
    return render_404 unless @article
    @article.tagstr = @article.tags2str
  end

  def update
    @article = Article.find_by_id params[:id]
    return render_404 unless @article
    if @article.update_attributes article_params
      @article.update_tags @article.tagstr
      # 保存图片
      current_user.post_cache_pictures_in_article @article
      flash.now[:success] = I18n.t "flash.success.update_article"
    else
      flash.now[:warning] = @article.errors.full_messages[0]
    end
    render 'edit'
  end

  private
    def article_params
      params.require(:article).permit :title, :content, :content_html, :tagstr, 
                                      :posted, :user_id, :category_id
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :check_signed_in, except: [:show]
  before_action :check_activated, except: [:show]

  before_action :find_article_by_id, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  before_action :delete_cache_pictures, only: [:new, :edit, :show]
  before_action :get_article_hold, only: [:new, :edit]

  layout 'blog'

  def index
    redirect_to user_path(current_user.username)
  end

  def show
    if current_user != @article.user && @article.posted.blank?
      return render_404
    end
    get_user_category_and_tags
    if @article.posted
      get_next_or_pre_article

      @comments = @article.comments
      @comment = Comment.new article: @article
      @comment_size = @article.comment_count

      @article.view_count += 1
      @article.save
    end
  end

  def new
    get_current_user_and_categories
    @article = current_user.articles.build
    set_article_hold_content
  end

  def edit
    get_current_user_and_categories @article.category_id
    @article.tagstr = @article.tags2str
    set_article_hold_content
  end

  def create
    get_current_user_and_categories article_params[:category_id]
    @article = current_user.articles.build article_params
    if @article.save
      @article.str2tags @article.tagstr
    else
      flash.now[:warning] = @article.errors.full_messages[0]
      return render 'new'
    end

    save_or_post_article
  end

  def update
    get_current_user_and_categories article_params[:category_id]
    if @article.update_attributes article_params
      @article.update_tags @article.tagstr
    else
      flash.now[:warning] = @article.errors.full_messages[0]
      return render 'edit'
    end

    save_or_post_article
  end

  def destroy
    @article.destroy
    flash[:success] = I18n.t "flash.success.delete_article", title: @article.title
    redirect_to drafts_user_path(current_user.username)
  end

  private
    def article_params
      params.require(:article).permit(:title, :category_id, :content, :content_html, :tagstr)
    end

    def get_current_user_and_categories(selected_category_id = 1)
      @user = current_user
      @category = current_user.categories.find_by id: selected_category_id
      @category ||= current_user.categories.first
      @categories = current_user.categories
    end

    def find_article_by_id
      @article = Article.find_by_id params[:id]
      return render_404 unless @article      
    end

    def correct_user
      render_404 unless current_user == @article.user
    end

    def get_user_category_and_tags
      return if @article.blank?
      @user = @article.user
      @category = @article.category
      @tags = @article.tags
    end

    def get_next_or_pre_article 
      return unless @user
      return unless @article.posted
      articles = @user.articles.where(posted: true).to_a
      return if articles.size < 2
      index = articles.index @article
      @next_article = @pre_article = nil
      @next_article = articles[index+1] if index < articles.size-1
      @pre_article = articles[index-1] if index > 0
    end

    def save_or_post_article
      # 标记图片已使用, 并关联文章
      current_user.post_cache_pictures_in_article @article
      current_user.hold(:article).update_attribute :cleaned, true

      if params[:article][:save]
        flash.now[:success] = I18n.t "flash.success.save_article"
        @article.update_attribute :posted, false
        render 'edit'
      elsif params[:article][:post]
        unless @article.posted
          @article.update_attribute :posted, true
          @article.update_attribute :created_at, Time.zone.now
        end
        redirect_to article_path(@article.id)
      else
        redirect_to root_path
      end
    end

    def delete_cache_pictures
      if user = current_user
        user.delete_cache_pictures
      end
    end

    # 获取文章的暂存数据
    def get_article_hold
       @hold = current_user.hold :article
    end

    # 设置暂存好的数据
    def set_article_hold_content
      return if @hold.blank? || @hold.cleaned?
      return unless @article
      # 编辑/创建
      if @article.id
        if @article.id == @hold.holdable_id
          set_hold_content
        end
      elsif @hold.holdable_id.blank?
        set_hold_content
      end
    end

    def set_hold_content
      @article.title = @hold.title
      @article.content = @hold.content
      @article.category_id = @hold.category_id
      @article.tagstr = @hold.tagstr
    end

end

app/helpers/articles_helper.rb
module ArticlesHelper
  include MarkdownHelper

  ## 已选中的分类项
  def category_selected_tag(category, opts = {})
    return if category.blank?
    content_tag :span, category.mname, opts
  end

  # 用户所有分类项
  def category_menu_li_tag(category, selected)
    return if category.blank?
    style = "category-item"
    style += " li-active" if selected
    category_content = content_tag :span, category.mname, class: 'content', value: category.id
    category_content += content_tag :span, '', class: 'setting fa fa-cog fa-fw', role: 'button' unless category.name == 'default'
    content_tag :li, link_to(category_content, '#'), class: style
  end

  # 文章分类标签
  def category_tag(user, category, opts={})
    return if user.blank? || category.blank?
    link_to category.mname, category_user_path(user.username, category.id), opts
  end


  # 关键字标签
  def tags_tag(user, tags)
    return if user.blank? || tags.blank?
    content = tags.map { |tag| link_to '# '+tag.name, tag_user_path(user.username, tag.id) }.join ' · '
    sanitize content
  end

  # 前一篇文章
  def pre_article_tag(pre_article)
    return if pre_article.blank?
    content = content_tag(:i, '', class: 'fa fa-chevron-left') + ' ' + pre_article.title
    link_to sanitize(content), article_path(pre_article)
  end

  # 后一篇文章
  def next_article_tag(next_article)
    return if next_article.blank?
    content = next_article.title + ' '+ content_tag(:i, '', class: 'fa fa-chevron-right')
    link_to sanitize(content), article_path(next_article)
  end

  # 显示文章部分内容
  def truncate_article_tag(article, opts={})
    return if article.blank? || article.content.blank?
    content = article.content.strip[0..200]
    # 格式化换行
    content = content.gsub(/#/, '').gsub /(\r\n)+/i, '<br>'
    # 省略号置换最后的换行符
    content = content.gsub /<br>$/i, ''
    content += "..."
    # 其他特殊字符由markdown渲染
    content = markdown_parser.render content
    content_tag :div, sanitize_markdown(content), opts
  end
end

app/views/admin/articles/_articles_table.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <%= content_tag :th, t("article.title") %>
      <%= content_tag :th, t("article.view_count") %>
      <%= content_tag :th, t("article.comment_count") %>
      <%= content_tag :th, t("article.user") %>
      <%= content_tag :th, t("article.category") %>
      <%= content_tag :th, t("article.tag") %>
      <%= content_tag :th, t("article.create_time") %>
      <%= content_tag :th, t("opt") %>
    </tr>
  </thead>
  <tbody>
    <% articles.each do |article| %>
      <tr>
        <%= content_tag :td, article.id %>
        <%= content_tag :td, article.title %>
        <%= content_tag :td, article.view_count %>
        <%= content_tag :td, article.comment_count %>
        <%= content_tag :td, article.user.username %>
        <%= content_tag :td, article.category.name %>
        <%= content_tag :td, article.tags2str %>
        <%= content_tag :td, mtime_tag(article.created_at) %>
        <%= content_tag :td do -%>
          <%= link_to t('update'), edit_admin_article_path(article.id) %> / 
          <%= link_to t('delete'), admin_article_path(article.id), value: article.id, method: 'DELETE', id: 'to-delete' %>
        <% end -%>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/articles/_new_or_edit.html.erb
<% provide :bodyclass, "admin" %>
<% provide :index, '2' %>
<div id="articles">
  <div class="boxed-group">
    <%= content_tag :h3, yield(:content_title) %>
    <div class="boxed-group-inner">
      <%= simple_form_for @article, url: yield(:form_url) do |f| %>
      <div class="row">
        <div class="col-md-8">
          <div class="form-group">
            <%= content_tag :span, t("article.title") %>
            <%= f.input_field :title, class: "form-control form-input-normal" %>
          </div>
          <div class="edit-body">
            <!-- 标签卡与工具栏 -->
            <div class="edit-body-header">
              <div class="post-edit-toolbar pull-right">
                <%= render 'features/markdown_toolbar' %>
              </div>
              <ul class="nav nav-tabs" id="edit-tabs">
                <%= content_tag :li, link_to(t("article.edit"), '#edit-content', class: 'edit-body-node edit-node', 'data-toggle': 'tab'), class: 'active' %>
                <%= content_tag :li, link_to(t("article.preview"), '#preview-content', class: 'edit-body-node preview-node', 'data-toggle': 'tab') %>
              </ul>
            </div>
            <!-- 编辑/预览区 -->
            <div class="tab-content edit-body-cotent" id="tab-content">
              <div class="tab-pane fade in active" id="edit-content">
                <%= f.input_field :content, as: :text, class: 'tabIndent edit-body-node edit-node', id: 'editor' %>
                <%= f.input_field :content_html, as: :hidden, id: 'content_html', disable: true %>
              </div>
              <div class="tab-pane fade" id="preview-content">
                <%= content_tag :div, '', class: 'edit-body-node preview-node standard markdown-body', id: 'previewer' %>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="form-group">
            <%= content_tag :span, t("article.user_id") %>
            <%= f.input_field :user_id, class: "form-control form-input-normal" %>
          </div>

          <div class="form-group">
            <%= content_tag :span, t("article.category_id") %>
            <%= f.input_field :category_id, class: "form-control form-input-normal" %>
          </div>

          <div class="form-group">
            <%= content_tag :span, t("article.tag") %>
            <%= f.input_field :tagstr, class: "form-control form-input-normal", id: "tag-input", placeholder: t("article.tag_tips") %>
          </div>

          <div class="form-group">
            <%= content_tag :span, t("article.post") %>
            <select selected="selected" class="select form-control form-input-normal" name="article[posted]" id="article_posted">
              <%= boolean_selected_tags f.object.posted %>
            </select>
          </div>

        </div>
      </div>
      <div class="form-group">
        <%= f.submit t("c-summary.article.new"), class: "btn btn-primary submit", onclick: 'set_content_html()' %>
      </div>
      <% end %>
    </div>
  </div>
</div>
<%= javascript_include_tag 'editor-markdown' %>

app/views/admin/articles/edit.html.erb
<% provide :pre_title, t("article.update_article") + ' | ' + t("console") %>
<% provide :content_title, t("article.update_article") %>
<% provide :form_url, admin_article_path(@article.id) %>

<%= render 'new_or_edit' %>

app/views/admin/articles/index.html.erb
<% provide :pre_title, t("console-nav.article") + ' | ' + t("console") %>
<% provide :bodyclass, "admin" %>
<% provide :index, '2' %>

<div id="users">
  <div class="boxed-group">
    <%= content_tag :h3, t("console-nav.article") %>
    <div class="boxed-group-inner">

      <ul class="nav nav-tabs">
        <%= content_tag :li, link_to(t("c-summary.total"), admin_articles_path), class: "#{'active' if @value == 1 }" %>

        <%= content_tag :li, link_to(t("c-summary.posted"), admin_articles_path(by: 'posted')), class: "#{'active' if @value == 2 }" %>

        <%= content_tag :li, link_to(t("c-summary.not_post"), admin_articles_path(by: 'unposted')), class: "#{'active' if @value == 3 }" %>

        <%= content_tag :a, href: new_admin_article_path, class: 'pull-right', title: t('c-summary.article.new') do -%>
          <%= content_tag :span, '', class: 'glyphicon glyphicon-plus' %>
        <% end -%>
      </ul>

      <div id="body-content">
        <%= render 'articles_table', articles: @articles %>
        <%= will_paginate @articles, renderer: WillPaginate::ActionView::BlogLinkRenderer %>
      </div>
    </div>
  </div>
</div>

<%= render 'admin/features/confirm_delete_dialog' %>

<script>
  $("#body-content").on("click", "#to-delete", function(){
      text = $(this).attr("value");
      text = "<%= j t('ask.article_delete.pre') %>" + text + "<%= j t('ask.article_delete.suf') %>";
      $("#confirm-delete .modal-body").html(text);
      $("#confirm-delete #confirm").attr('href', $(this).attr('href'));
      $("#confirm-delete").modal();
      return false;
  });
</script>

app/views/admin/articles/new.html.erb
<% provide :pre_title, t("c-summary.article.new") + ' | ' + t("console") %>
<% provide :content_title, t("c-summary.article.new") %>
<% provide :form_url, admin_articles_path %>

<%= render 'new_or_edit' %>