config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  get '/signup' => 'accounts#new'
  post '/signup' => 'accounts#create'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  delete '/signout' => 'sessions#destroy'

  namespace :accounts, as: 'accounts', constraints: { id: User::USERNAME_FORMAT } do
    get '/passwords/forgot' => 'passwords#new'
    post '/passwords/forgot' => 'passwords#create'

    resources :passwords, only: [:edit, :update]
    resources :activations, only: [:new, :edit] 
  end
  
  resource :account, only: [:edit] do 
    patch '/edit', action: :update
    put '/edit', action: :update
  end

  constraints( id: /\d+/ ) do
    resources :articles
    resources :categories, only: [:create, :update, :destroy]
    resources :comments, only: [:create, :edit, :update, :destroy] do
      member do
        get :reply
      end
    end
  end

  # 上传图片
  match '/pictures' => 'pictures#create', via: [:post, :patch, :put]
  # 暂存文章/简历
  match '/holds' => 'holds#update', via: [:post, :patch, :put]

  namespace :admin, as: 'admin' do
    root 'home#index', as: 'index'
    resources :users, except: :show
    resources :articles, except: :show
    resources :categories, except: :show
    resources :tags, except: :show
    resources :comments, except: :show
    resources :pictures, only: [:index, :destroy, :create]
  end

  # users相关路由最后
  resources :users, only: [:show] , path: '' , constraints: { id: User::USERNAME_FORMAT } do
    member do
      get :categories
      get :aboutme
      get :drafts
      get :archive
      get '/categories/:category_id', as: 'category', to: 'users#category'
      get '/tags/:tag_id', as: 'tag', to: 'users#tag'
      get '/search', to: 'search#index'
      get '/resume', to: 'resumes#show'
      match '/resume', to: 'resumes#update', via: [:patch, :put]
      get '/resume/edit', to: 'resumes#edit'
    end
  end

end

app/views/shared/_blog_footer.html.erb
<footer id="footer" class="text-muted">
  <div class="container">
    <span class="site-footer-info">  © 2016 hikumho. Powered by Rails. </span>
    <span class="site-footer-links">
      <a href="https://www.github.com/hikumho">Github</a> |
      <a href="mailto:hi.jinhu.zhang@gmail.com">Email</a>
    </span>
  </div>
</footer>

app/views/shared/_blog_header.html.erb
<!-- 导航栏 -->
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- 导航栏首部 -->
    <div class="navbar-header">
      <!-- Logo -->
      <%= link_to image_tag("logo.png", alt:"Milog", class: "logo"), root_path, class: "navbar-brand" %>
      <!-- 切换语系 -->
      <%= link_to_locale request.path, mclass: "navbar-text switch-lang" %>

      <%= content_tag(:span, "#{capitalize_name(@user)}'s Blog", class: "navbar-text ") if current_user != @user %>
      <!-- 屏幕<=420px时显示 -->
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapse-nav">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <!-- 已登录, 显示操作菜单 -->
    <% if signed_in? %>
      <ul class="nav navbar-nav navbar-right navbar-footer drop-nav" >
        <!-- 后台操作 -->
        <% if current_user.admin? %>
        <li>
          <%= link_to content_tag(:i, '', class: 'glyphicon glyphicon-console header-console'), admin_index_path, title: t('console') %>
        </li>
        <% end %>
        <!-- 新建类操作 -->
        <li class="dropdown dropdown-opt">
          <a class="dropdown-toggle" data-toggle="dropdown" role="button" >
            <span class="glyphicon glyphicon-plus"></span>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <%= content_tag :li, link_to(t("new_blog"), new_article_path) %>
            <%= content_tag :li, link_to(t("edit_resume"), resume_edit_user_path(@user.username)) %>
          </ul>
        </li>
        <!-- 设置类操作 -->
        <li class="dropdown dropdown-setting">
          <a class="dropdown-toggle" data-toggle="dropdown" role="button" >
            <!-- 头像 -->
            <%= avatar_tag current_user, :xs %>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <%= content_tag :li, link_to(capitalize_name(current_user), user_path(current_user.username)) %>
            <%= content_tag :li, content_tag(:div, '', class:"divider") %>
            <%= content_tag :li, link_to(t("account_profile"), edit_account_path) %>
            <%= content_tag :li, link_to(t("resume"), resume_user_path(@user.username)) %>
            <%= content_tag :li, link_to(t("drafts"), drafts_user_path(@user.username)) %>
            <%= content_tag :li, content_tag(:div, '', class:"divider") %>
            <%= content_tag :li, link_to(t("signout"), signout_path, method: 'delete') %>
          </ul>
        </li>
      </ul>
    <% else %>
      <!-- 登录注册 -->
      <div class="navbar-right navbar-footer login-group">
        <%= link_to t("signup"), signup_path, class: "navbar-text" %>
        <%= link_to t("signin"), signin_path, class: "navbar-text" %>
      </div>
    <% end %>
    
    <!-- 主菜单项 -->
    <% if yield(:inadmin).blank? %>
    <div class="collapse navbar-collapse" id="collapse-nav">
      <ul class="nav navbar-nav navbar-center main-nav">
        <%= content_tag :li, link_to(t("home"), user_path(@user.username)) %>
        <%= content_tag :li, link_to(t("category"), categories_user_path(@user.username)) %>
        <%= content_tag :li, link_to(t("archive"), archive_user_path(@user.username)) %>
        <%= content_tag :li, link_to(t("aboutme"), aboutme_user_path(@user.username)) %>
        <%= content_tag :li, link_to(t("search"), "#", id: 'search') %>
      </ul>
    </div>
    <% end %>
  </div>
</nav>

app/views/shared/_flash_messages_inner.html.erb
<% unless flash.empty? %>
<div class="col-md-11 col-center-block content-wrap" style="width: 100%;">
  <% flash.each do | message_type, message | %>
  <div class="flash-alert-inner alert alert-<%= "#{message_type}" %>">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <%= sanitize message %>
  </div>
  <% end %>
</div>
<% end %>

app/views/shared/_flash_messages_jscall.html.erb
<div class="col-md-11 col-center-block content-wrap" id="flash_warning" style="display: none; width: 100%;">
  <div class="flash-alert-inner alert alert-warning">
    <a href="#" class="close" aria-label="close">&times;</a>
    <span id="message"><span>
  </div>
</div>

app/views/shared/_flash_messages_top.html.erb
<% flash.each do | message_type, message | %>
  <div class="flash-alert-top alert alert-<%= "#{message_type}" %>">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <%= sanitize message %>
  </div>
<% end %>

app/views/shared/_form_error_messages.html.erb
<% if object && object.errors.any? %>
<div class="form-error">
  <span class="form-error-field"><%= object.errors.full_messages[0] %></span>
  <span class="glyphicon glyphicon-info-sign icon"></span>
</div>
<% end %>

app/views/shared/_page_head.html.erb
<head>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title><%= title yield(:pre_title) %></title>    
  
  <script>
    App.locale = "<%= I18n.locale %>";
  </script>
</head>

app/views/shared/_signin_form.html.erb
<!-- 登录表单 -->
<%= simple_form_for :session, url: signin_path do |f| %>
<%= render "shared/form_error_messages", object: @user %>
<div class="form-group form-group-icon">
	<%= f.email_field :email, placeholder: t("email"), class: "form-input email" %>
	<span class="glyphicon glyphicon-envelope icon"></span>
</div>
<div class="form-group form-group-icon">
	<%= f.password_field :password, placeholder: t("password"), class: "form-input password" %>
	<span class="glyphicon glyphicon-lock icon"></span>
</div>
<div class="form-group">
	<%= f.button :submit, t("signin"), class: "btn btn-primary btn-block submit", id: "signin" %>
</div>
<div class="login-setting">
	<div class="checkbox">
		<span class="remember-me"><%= f.input_field :remember_me, as: :boolean, boolean_style: :inline %><%= t "login.remember_me" %></span>
	</div>
  <%= link_to t("login.forget_me"), accounts_passwords_forgot_path, class: "forget-me" %>
</div>
<% end %>

app/views/shared/_signup_form.html.erb
<!-- 注册表单 -->
<%= simple_form_for @user, url: signup_path do |f| %>
<%= render "shared/form_error_messages", object: f.object %>
<div class="form-group form-group-icon">
	<%= f.input_field :username, placeholder: t("username"), class: "form-input name" %>
	<span class="glyphicon glyphicon-user icon"></span>
</div>
<div class="form-group form-group-icon">
	<%= f.email_field :email, placeholder: t("email"), class: "form-input email" %>
	<span class="glyphicon glyphicon-envelope icon"></span>
</div>
<div class="form-group form-group-icon">
	<%= f.password_field :password, placeholder: t("password"), class: "form-input password" %>
	<span class="glyphicon glyphicon-lock icon"></span>
</div>
<div class="form-group form-group-icon">
	<%= f.password_field :password_confirmation, placeholder: t("password_confirmation"), class: "form-input password" %>
	<span class="glyphicon glyphicon-lock icon"></span>
</div>
<div class="form-group">
	<%= f.button :submit, t("signup"), class: "btn btn-primary btn-block submit", id: "signup" %>
</div>
<% end %>