config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  get '/signup' => 'accounts#new'
  post '/signup' => 'accounts#create'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  delete '/signout' => 'sessions#destroy'

  namespace :accounts, as: 'accounts', constraints: { id: User::USERNAME_FORMAT } do
    get '/passwords/forgot' => 'passwords#new'
    post '/passwords/forgot' => 'passwords#create'

    resources :passwords, only: [:edit, :update]
    resources :activations, only: [:new, :edit] 
  end
  
  resource :account, only: [:edit] do 
    patch '/edit', action: :update
    put '/edit', action: :update
  end

  constraints( id: /\d+/ ) do
    resources :articles
    resources :categories, only: [:create, :update, :destroy]
    resources :comments, only: [:create, :edit, :update, :destroy] do
      member do
        get :reply
      end
    end
  end

  # 上传图片
  match '/pictures' => 'pictures#create', via: [:post, :patch, :put]
  # 暂存文章/简历
  match '/holds' => 'holds#update', via: [:post, :patch, :put]

  namespace :admin, as: 'admin' do
    root 'home#index', as: 'index'
    resources :users, except: :show
    resources :articles, except: :show
    resources :categories, except: :show
    resources :tags, except: :show
    resources :comments, except: :show
    resources :pictures, only: [:index, :destroy, :create]
  end

  # users相关路由最后
  resources :users, only: [:show] , path: '' , constraints: { id: User::USERNAME_FORMAT } do
    member do
      get :categories
      get :aboutme
      get :drafts
      get :archive
      get '/categories/:category_id', as: 'category', to: 'users#category'
      get '/tags/:tag_id', as: 'tag', to: 'users#tag'
      get '/search', to: 'search#index'
      get '/resume', to: 'resumes#show'
      match '/resume', to: 'resumes#update', via: [:patch, :put]
      get '/resume/edit', to: 'resumes#edit'
    end
  end

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::ApplicationController

  def index
    @summary = {
      user:      { total: User.all.size,     normal: User.normal.size, 
                   admin: User.admin.size,   disabled: User.disabled.size  },
      article:   { total: Article.all.size,  posted: Article.posted.size, 
                   unposted: Article.unposted.size },
      category:  { total: Category.all.size, used: Category.used.size,
                   unused: Category.unused.size },
      tag:       { total: Tag.all.size,      used: Tag.used.size,
                   unused: Tag.unused.size },
      comment:   { total: Comment.all.size,  posted: Comment.posted.size,
                   deleting: Comment.deleting.size },
      picture:   { total: Picture.all.size,  posted: Picture.posted.size,
                   unposted: Picture.unposted.size }
    }
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if signed_in?
      redirect_to user_path(current_user.username)
    else
      redirect_to signin_path
    end
  end
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
  def user_state(user)
    return nil if user.blank?
    case user.state
      when 0
        I18n.t "c-summary.user.disabled"
      when 1
        I18n.t "c-summary.user.normal"
      when 2
        I18n.t "c-summary.user.admin"
    end
  end

  def user_state_selected_tags(selected_value)
    value = 
      if selected_value.blank?
        1
      else
        selected_value
      end
    options = ""
    states = [I18n.t("c-summary.user.disabled"), I18n.t("c-summary.user.normal"), I18n.t("c-summary.user.admin")]
    states.each_with_index do |name, index|
      options += 
        if index != value
          content_tag :option, name, value: index 
        else
          content_tag :option, name, value: index, selected: 'selected'
        end
    end
    raw options
  end

  def boolean_selected_tags(selected_value)
    value = selected_value
    value = false if selected_value.blank?
    options = ""
    state = [true, false]
    state.each do |item|
      options +=
        if item != value
          content_tag :option, item, value: item 
        else
          content_tag :option, item, value: item, selected: 'selected'
        end
    end
    raw options
  end

end

app/views/admin/home/index.html.erb
<% provide :pre_title, t("console-nav.summary") + ' | ' + t("console") %>
<% provide :bodyclass, "admin" %>
<% provide :index, '0' %>
<div id="summary">
  <div class="boxed-group">
    <%= content_tag :h3, t("console-nav.summary") %>
    <div class="boxed-group-inner">

      <div class="summary-group" id="users">
        <%= content_tag :h4, class: 'title' do -%>
          <%= link_to content_tag(:span, @summary[:user][:total] > 0 ? t("c-summary.user.other", size: @summary[:user][:total]) : t("c-summary.user.zero") ), admin_users_path %>
          <a data-toggle="collapse" href="#user-table">
            <span class="caret pull-right" ></span>
          </a>
        <% end -%>
        <div class="collapse in" id="user-table">
          <table class="table" >
            <tbody>
              <tr>
                <td>
                  <%= content_tag :a, href: admin_users_path(by: 'normal') do -%>
                    <%= content_tag :span, t("c-summary.user.normal"), class: 'name' %>
                    <%= content_tag :span, @summary[:user][:normal], class: 'count' %>
                  <% end -%>
                </td>
                <td >
                  <%= content_tag :a, href: admin_users_path(by: 'admin') do -%>
                    <%= content_tag :span, t("c-summary.user.admin"), class: 'name' %>
                    <%= content_tag :span, @summary[:user][:admin], class: 'count' %>
                  <% end -%>
                </td>
                <td >
                  <%= content_tag :a, href: admin_users_path(by: 'disabled') do -%>
                    <%= content_tag :span, t("c-summary.user.disabled"), class: 'name' %>
                    <%= content_tag :span, @summary[:user][:disabled], class: 'count' %>
                  <% end %>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <div class="summary-group" id="articles">
        <%= content_tag :h4, class: 'title' do -%>
          <%= link_to content_tag(:span, @summary[:article][:total] > 0 ? t("c-summary.article.other", size: @summary[:article][:total]) : t("c-summary.article.zero") ), admin_articles_path %>
          <a data-toggle="collapse" href="#article-table">
            <span class="caret pull-right" ></span>
          </a>
        <% end -%>

        <div class="collapse in" id="article-table">
          <table class="table" >
            <tbody>
              <tr>
                <td>
                  <%= content_tag :a, href: admin_articles_path(by: 'posted') do -%>
                    <%= content_tag :span, t("c-summary.posted"), class: 'name' %>
                    <%= content_tag :span, @summary[:article][:posted], class: 'count' %>
                  <% end -%>
                </td>
                <td >
                  <%= content_tag :a, href: admin_articles_path(by: 'unposted') do -%>
                    <%= content_tag :span, t("c-summary.not_post"), class: 'name' %>
                    <%= content_tag :span, @summary[:article][:unposted], class: 'count' %>
                  <% end -%>
                </td>
              </tr>
            </tbody>
          </table>
        </div>        
      </div>

      <div class="summary-group" id="categories">
        <%= content_tag :h4, class: 'title' do -%>
          <%= link_to content_tag(:span, @summary[:category][:total] > 0 ? t("c-summary.category.other", size: @summary[:category][:total]) : t("c-summary.category.zero") ), admin_categories_path %>
          <a data-toggle="collapse" href="#category-table">
            <span class="caret pull-right" ></span>
          </a>
        <% end -%>

        <div class="collapse in" id="category-table">
          <table class="table" >
            <tbody>
              <tr>
                <td>
                  <%= content_tag :a, href: admin_categories_path(by: 'used') do -%>
                    <%= content_tag :span, t("c-summary.used"), class: 'name' %>
                    <%= content_tag :span, @summary[:category][:used], class: 'count' %>
                  <% end -%>
                </td>
                <td >
                  <%= content_tag :a, href: admin_categories_path(by: 'unused') do -%>
                    <%= content_tag :span, t("c-summary.not_use"), class: 'name' %>
                    <%= content_tag :span, @summary[:category][:unused], class: 'count' %>
                  <% end -%>
                </td>
              </tr>
            </tbody>
          </table>
        </div>        
      </div>

      <div class="summary-group" id="tags">
        <%= content_tag :h4, class: 'title' do -%>
          <%= link_to content_tag(:span, @summary[:tag][:total] > 0 ? t("c-summary.tag.other", size: @summary[:tag][:total]) : t("c-summary.tag.zero") ), admin_tags_path %>
          <a data-toggle="collapse" href="#tag-table">
            <span class="caret pull-right" ></span>
          </a>
        <% end -%>

        <div class="collapse in" id="tag-table">
          <table class="table" >
            <tbody>
              <tr>
                <td>
                  <%= content_tag :a, href: admin_tags_path(by: 'used') do -%>
                    <%= content_tag :span, t("c-summary.used"), class: 'name' %>
                    <%= content_tag :span, @summary[:tag][:used], class: 'count' %>
                  <% end -%>
                </td>
                <td >
                  <%= content_tag :a, href: admin_tags_path(by: 'unused') do -%>
                    <%= content_tag :span, t("c-summary.not_use"), class: 'name' %>
                    <%= content_tag :span, @summary[:tag][:unused], class: 'count' %>
                  <% end -%>
                </td>
              </tr>
            </tbody>
          </table>
        </div>        
      </div>

      <div class="summary-group" id="comments">
        <%= content_tag :h4, class: 'title' do -%>
          <%= link_to content_tag(:span, @summary[:comment][:total] > 0 ? t("c-summary.comment.other", size: @summary[:comment][:total]) : t("c-summary.comment.zero") ), admin_comments_path %>
          <a data-toggle="collapse" href="#comment-table">
            <span class="caret pull-right" ></span>
          </a>
        <% end -%>

        <div class="collapse in" id="comment-table">
          <table class="table" >
            <tbody>
              <tr>
                <td>
                  <%= content_tag :a, href: admin_comments_path(by: 'posted') do -%>
                    <%= content_tag :span, t("c-summary.posted"), class: 'name' %>
                    <%= content_tag :span, @summary[:comment][:posted], class: 'count' %>
                  <% end -%>
                </td>
                <td >
                  <%= content_tag :a, href: admin_comments_path(by: 'deleting') do -%>
                    <%= content_tag :span, t("c-summary.deleting"), class: 'name' %>
                    <%= content_tag :span, @summary[:comment][:deleting], class: 'count' %>
                  <% end -%>
                </td>
              </tr>
            </tbody>
          </table>
        </div>        
      </div>

      <div class="summary-group" id="pictures">
        <%= content_tag :h4, class: 'title' do -%>
          <%= link_to content_tag(:span, @summary[:picture][:total] > 0 ? t("c-summary.picture.other", size: @summary[:picture][:total]) : t("c-summary.picture.zero") ), admin_pictures_path %>
          <a data-toggle="collapse" href="#picture-table">
            <span class="caret pull-right" ></span>
          </a>
        <% end -%>

        <div class="collapse in" id="picture-table">
          <table class="table" >
            <tbody>
              <tr>
                <td>
                  <%= content_tag :a, href: admin_pictures_path(by: 'posted') do -%>
                    <%= content_tag :span, t("c-summary.used"), class: 'name' %>
                    <%= content_tag :span, @summary[:picture][:posted], class: 'count' %>
                  <% end -%>
                </td>
                <td >
                  <%= content_tag :a, href: admin_pictures_path(by: 'unposted') do -%>
                    <%= content_tag :span, t("c-summary.will_delete"), class: 'name' %>
                    <%= content_tag :span, @summary[:picture][:unposted], class: 'count' %>
                  <% end -%>
                </td>
              </tr>
            </tbody>
          </table>
        </div>        
      </div>
    </div>
  </div>
</div>